### PR TITLE
Check `args` slice bounds in `get` and `put` functions

### LINKED ISSUE #10: `get` command panics without second argument
The `get` command currently requires two arguments, a source path and destination path. Running it with one argument, e.g. `dbxcli get /dir/file`, throws this error:

```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x4b2ce0, 0xc820010070)
	/home/travis/.gimme/versions/go1.6.2.linux.amd64/src/runtime/panic.go:481 +0x3e6
github.com/dropbox/dbxcli/cmd.get(0x7db940, 0xc820011200, 0x1, 0x1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dropbox/dbxcli/cmd/get.go:31 +0x59a
github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra.(*Command).execute(0x7db940, 0xc8200111b0, 0x1, 0x1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra/command.go:561 +0x62c
github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x7dd140, 0x7db940, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra/command.go:651 +0x55c
github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra.(*Command).Execute(0x7dd140, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra/command.go:610 +0x2d
github.com/dropbox/dbxcli/cmd.Execute()
	/home/travis/gopath/src/github.com/dropbox/dbxcli/cmd/root.go:213 +0x23
main.main()
	/home/travis/gopath/src/github.com/dropbox/dbxcli/main.go:43 +0x14
```

In this situation I think it would be more intuitive to download the file into the current working directory, just like `sftp` and similar tools do.

### PR DESCRIPTION
**Pull request by waits**
This adds a bounds check before accessing the `args` slice in the `get` and `put` functions. This has two effects:

1. Displays a friendly error when the first argument (the source path) is not specified, instead of panicking.
2. Allows these commands to work intuitively without a second argument (the destination path) by defaulting the destination path to be the base segment of the source path. This was already partially written into the `get` function but it didn't work and panicked instead.

Fixes #10.

### CODE REVIEW

File: cmd/get.go [hunk 1]
```diff
@@ -27,11 +28,21 @@ import (
...
+
 	src, err := validatePath(args[0])
-	dst := args[1]
+	if err != nil {
+		return
+	}
 
-	if dst == "" {
+	var dst string
+	if len(args) < 2 {
```
Comment (diwakergupta) [inline cmd/get.go]: Given the check above, this can really only be `len(args) == 1` right?

File: cmd/get.go [hunk 2]
```diff
@@ -27,11 +28,21 @@ import (
...
+		// If a destination is not specified use the base of the source path
 		dst = path.Base(src)
```
Comment (diwakergupta) [inline cmd/get.go]: Why not just initialize dst to Base(src) and then use args[1] if len == 2. On that note, should we also error out if len > 2?

File: cmd/get.go (hunk 1 above)
Comment (waits) [inline cmd/get.go]: Thanks, I didn't catch that.

File: cmd/get.go (hunk 2 above)
Comment (waits) [inline cmd/get.go]: You're right, that's much cleaner. I thought assigning `dst` twice would be unnecessary, but it really just cluttered up the code with an extra `else`.

Comment (waits) [inline cmd/get.go]: I agree we should error out with too many arguments. Most other CLI tools do the same I believe.

**Comment by waits** [comment]
@diwakergupta I added two commits based on your feedback.

- I'm returning an error if 0 or > 2 arguments are passed. Is my one error message good enough for both conditions?
- With those bounds known, I only need to check if `len == 2`.
- I also replaced `len(args) < 1` with `len(args) == 0` because the [spec](https://golang.org/ref/spec#Length_and_capacity) says len will never return < 0. Common sense says it shouldn't, but I thought it good to check for edge cases anyways.

File: cmd/get.go [hunk 3]
```diff
@@ -27,11 +28,19 @@ import (
 )
 
 func get(cmd *cobra.Command, args []string) (err error) {
+	if len(args) == 0 || len(args) > 2 {
+		return errors.New("`get` requires 1 or 2 arguments")
```
Comment (diwakergupta) [inline cmd/get.go]: Maybe say "`get` requires `src` and/or `dst` arguments"?

File: cmd/put.go [hunk 4]
```diff
@@ -56,10 +58,19 @@ func uploadChunked(r io.Reader, commitInfo *files.CommitInfo, sizeTotal int64) (
 }
 
 func put(cmd *cobra.Command, args []string) (err error) {
+	if len(args) == 0 || len(args) > 2 {
+		return errors.New("`put` requires 1 or 2 arguments")
```
Comment (diwakergupta) [inline cmd/put.go]: Same comment as above. Otherwise LG.

File: cmd/get.go (hunk 3 above)
Comment (waits) [inline cmd/get.go]: That *could* be interpreted as meaning it's OK to pass `dst` without `src`. I don't think that's likely though.

**Comment by waits** [comment]
Added 8655d72 with your suggested error text.

**Comment by diwakergupta** [comment]
Thanks!
